%% 2-D FEM
% Solve 2-D Harmonic Oscillator Problem
% -(1/2) * Δu + (x²+y²)/2 * u = λ * u , on Ω = [-10, 10]²
%                           u = 0     , on ∂Ω
% Use standard FEM/ALS/2-site DMRG and compare their calculation accuracy


%% Set-up
v = @(x, y)(1/2*(x^2+y^2));
xy_range = 20;
xy_ep = [-xy_range/2 xy_range/2 -xy_range/2 xy_range/2];
gqr = [5 5];
tol = 1e-14;
rmax = 10;


%% Reference
N_ref = 2^8+1;
[A_ref, B_ref, M_ref] = fem_mat_2d_boost(v, N_ref, xy_ep, ...
                                  {'Laplace', 'Potential', 'Mass'}, gqr);
A_ref = 1/2*A_ref;
[x_ref, lambda_ref] = eigs(A_ref+B_ref, M_ref, 1, 'smallestabs', ...
                           'Tolerance', 1e-14, 'MaxIterations', 10^8);


%% Solve the problem
d_list = 3:7;
N_list = 2.^(d_list)+1;
[x_err_fem, x_err_1, x_err_2, ...
 lambda_fem, lambda_1, lambda_2] = deal(N_list);
[A_fem, B_fem, M_fem, A_qtt, B_qtt, M_qtt, H_qtt, ...
 x_fem, x_1, x_2] = deal(cell(length(N_list), 1));

for i = 1:length(N_list)
    % Stiffness matrices
    [A_fem{i}, B_fem{i}, M_fem{i}] = fem_mat_2d_boost(v, N_list(i), ...
                                     xy_ep, {'Laplace', 'Potential', ...
                                     'Mass'}, gqr);
    A_fem{i} = 1/2*A_fem{i};

    % Solved by eigs()
    [x_fem{i}, lambda_fem(i)] = eigs(A_fem{i}+B_fem{i}, M_fem{i}, ...
                                     1, 'smallestabs', ...
                                     'Tolerance', 1e-14, ...
                                     'MaxIterations', 10^8);

    % QTT of stiffness matrices and start TT-vector
    A_qtt{i} = tt_qband(A_fem{i}, tol);
    B_qtt{i} = tt_qband(B_fem{i}, tol);
    M_qtt{i} = tt_qband(M_fem{i}, tol);
    x0 = tt_rand(2, 2*d_list(i), rmax);
    H_qtt{i} = round(A_qtt{i}+B_qtt{i}, tol);

    % Solved by 1-site DMRG
    [x_1{i}, lambda_1(i)] = dmrg2(H_qtt{i}, M_qtt{i}, tol, ...
                                  'numblocks', 1, 'rmax', rmax, 'x0', x0);

    % Solved by 1-site DMRG
    [x_2{i}, lambda_2(i)] = dmrg2(H_qtt{i}, M_qtt{i}, tol, ...
                                  'numblocks', 2, 'rmax', rmax, 'x0', x0);

end


%% Plot
% Annotation
ann_text = ['Problem:\enspace$(\omega={\hbar}^{-1}, m={\hbar}^2)$', ...
            newline, '$-\frac{1}{2}{\Delta}u+\frac{1}{2}(x^2+y^2)u=', ...
            '{\lambda}u\enspace$ on $\enspace\Omega=[-', ...
            num2str(xy_range/2), ',', num2str(xy_range/2), ']^2$', ...
            newline, '\quad$\qquad\qquad\qquad\quad\,\,\,u = 0', ...
            '\enspace\:\enspace$ on $\enspace\partial\Omega$', newline, ...
            'Tolerance = $10^{-14},\quad$Max TT Rank = $10$', ...
            newline, 'Reference:$\;d=8$'];

% Error of eigen value
fem_err_plot(xy_range./N_list, ...
             abs([lambda_fem', lambda_1', lambda_2']-lambda_ref), 10, ...
             'h', 'err', -0.9:0.1:0.4, -3.8:0.2:0, [2 0.53], ...
             ['Eigen Value Error ($d = 3\sim7$)', newline, ...
              '2D Harmonic Oscillator with Dirichlet Boundary'], ...
             'Method', {'eigs()', '1-site DMRG(ALS)', '2-site DMRG'}, ...
             [-0.4 -3.2], ann_text)

% L2 error of eigen function
err_type = M_ref;
for i = 1:length(N_list)
    x_err_fem(i) = fem_err_2d_simple(x_fem{i}, x_ref, xy_ep, ...
                   err_type, gqr);
    x_err_1(i) = fem_err_2d_simple(full(x_1{i}), x_ref, xy_ep, ...
                                   err_type, gqr);
    x_err_2(i) = fem_err_2d_simple(full(x_2{i}), x_ref, xy_ep, ...
                                   err_type, gqr);
end
fem_err_plot(xy_range./N_list, [x_err_fem', x_err_1', x_err_2'], 10, ...
             'h', 'err', -0.9:0.1:0.4, -3.8:0.2:0, [2 0.54], ...
             ['Eigen Function $L_2$ Error ($d = 3\sim7$)', newline, ...
              '2D Harmonic Oscillator with Dirichlet Boundary'], ...
              'Method', {'eigs()', '1-site DMRG(ALS)', '2-site DMRG'}, ...
              [-0.4 -3.1], ann_text)

% H1 error of eigen function
err_type = 2*A_ref+M_ref;
for i = 1:length(N_list)
    x_err_fem(i) = fem_err_2d_simple(x_fem{i}, x_ref, xy_ep, ...
                                     err_type, gqr);
    x_err_1(i) = fem_err_2d_simple(full(x_1{i}), x_ref, xy_ep, ...
                                   err_type, gqr);
    x_err_2(i) = fem_err_2d_simple(full(x_2{i}), x_ref, xy_ep, ...
                                   err_type, gqr);
end
fem_err_plot(xy_range./N_list, [x_err_fem', x_err_1', x_err_2'], 10, ...
             'h', 'err', -0.9:0.1:0.4, -2.8:0.2:0, [1 0.59], ...
             ['Eigen Function $H^1$ Error ($d = 3\sim7$)', newline, ...
              '2D Harmonic Oscillator with Dirichlet Boundary'], ...
              'Method', {'eigs()', '1-site DMRG(ALS)', '2-site DMRG'}, ...
              [-0.4 -2.3], ann_text)